### ISSUE TITLE
/token post does not include redirect_uri

### ISSUE THREAD

**Issue by cooljacob204** [Uber5/react-pkce#5]
Hey All, running into an issue with rails and doorkeeper because the redirect_uri is not included in the /token request.

My understanding of the o-auth spec is that it is required if included in the authorization request: https://tools.ietf.org/html/rfc6749#section-4.1.3.

**Comment by Chris927** [comment]
@cooljacob204 thanks for raising this, I believe you are right!

Your merge request is however not a general solution: If the `redirect_uri` contains other query parameters, you would discard them by splitting at the `?` character.

I'm busy implementing a solution by storing the original `redirect_uri` in local storage, I shall publish this shortly.

**Comment by cooljacob204** [comment]
I don't think it would matter because this is only splitting it for the redirect_uri which should not contain any parameters.

**Comment by Chris927** [comment]
I think it does matter, the `redirect_uri` could be any valid url of the React app.

In any case, I've changed it as described, upgraded dependencies, and published the package (version v0.9.11). Let me know if okay now.

**Comment by cooljacob204** [comment]
Ahh, sorry you are correct! I was mixing up URL and URI.

Latest changes resolved my issue.
