### ISSUE TITLE
Token is saved with `"` to SessionStorage

### ISSUE THREAD

**Issue by brumik** [Uber5/react-pkce#9]
I am using the session storage to retrieve the tokens when need to call the API. This returns the token correctly but with extra quotation marks.

Expected token to be returned:
`this is my super secret token`

Returned token:
`"this is my super secret token"`

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**
